name: Fresh-bot

on:
  schedule:
    # Run every day at 1am
    - cron: '* * * * *'
  push:
    branches: [ master ]

jobs:
  fresh-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Bump stale issues
        uses: c-hive/fresh-bot@v1
        with:
          GITHUB_TOKEN: 1b7be1b17230270ac8de57c9cfc3f21092067674 # ${{ secrets.PERSONAL_ACCESS_TOKEN }}
