name: Bump stale issues

on:
  schedule:
    # Run every day at 1am
    - cron: '* * * * *'
  push:
    branches: [ master ]

jobs:
  fresh-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Bump stale issues
        uses: c-hive/fresh-bot@v1
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN }} # Needs `repo` scope
